backend:
  name: github
  repo: internalarchive/IA-News-Site
  branch: main
  site_domain: ianews.netlify.app

media_folder: "docs/images"
public_folder: "/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "docs/blog/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'docs/about.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }